%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-sot-core
Version:        4.11.5
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS sot-core package

License:        BSD
URL:            http://stack-of-tasks.github.io
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python3-devel
Requires:       ros-noetic-catkin
Requires:       ros-noetic-dynamic-graph
Requires:       ros-noetic-dynamic-graph-python
Requires:       ros-noetic-pinocchio
BuildRequires:  boost-devel
BuildRequires:  boost-python3-devel
BuildRequires:  cmake
BuildRequires:  doxygen
BuildRequires:  ros-noetic-dynamic-graph
BuildRequires:  ros-noetic-dynamic-graph-python
BuildRequires:  ros-noetic-pinocchio
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Hierarchical task solver plug-in for dynamic-graph

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/noetic

%changelog
* Thu Mar 11 2021 Guilhem Saurel <guilhem.saurel@laas.fr> - 4.11.5-1
- Autogenerated by Bloom

* Tue Mar 02 2021 Guilhem Saurel <guilhem.saurel@laas.fr> - 4.11.4-6
- Autogenerated by Bloom

* Tue Mar 02 2021 Guilhem Saurel <guilhem.saurel@laas.fr> - 4.11.4-5
- Autogenerated by Bloom

* Tue Mar 02 2021 Guilhem Saurel <guilhem.saurel@laas.fr> - 4.11.4-4
- Autogenerated by Bloom

* Tue Feb 23 2021 Guilhem Saurel <guilhem.saurel@laas.fr> - 4.11.4-3
- Autogenerated by Bloom

* Tue Feb 23 2021 Guilhem Saurel <guilhem.saurel@laas.fr> - 4.11.4-2
- Autogenerated by Bloom

* Wed Feb 10 2021 Guilhem Saurel <guilhem.saurel@laas.fr> - 4.11.4-1
- Autogenerated by Bloom

* Fri Nov 27 2020 Olivier Stasse <ostasse@laas.fr> - 4.11.3-2
- Autogenerated by Bloom

* Fri Nov 27 2020 Olivier Stasse <ostasse@laas.fr> - 4.11.3-1
- Autogenerated by Bloom

* Sat Nov 21 2020 Olivier Stasse <ostasse@laas.fr> - 4.11.2-3
- Autogenerated by Bloom

* Mon Nov 16 2020 Olivier Stasse <ostasse@laas.fr> - 4.11.2-2
- Autogenerated by Bloom

* Mon Nov 16 2020 Olivier Stasse <ostasse@laas.fr> - 4.11.2-1
- Autogenerated by Bloom

* Thu Oct 15 2020 Olivier Stasse <ostasse@laas.fr> - 4.10.1-5
- Autogenerated by Bloom

* Thu Oct 15 2020 Olivier Stasse <ostasse@laas.fr> - 4.10.1-4
- Autogenerated by Bloom

* Thu Oct 08 2020 Olivier Stasse <ostasse@laas.fr> - 4.10.1-3
- Autogenerated by Bloom

* Wed Oct 07 2020 Olivier Stasse <ostasse@laas.fr> - 4.10.1-2
- Autogenerated by Bloom

* Thu Oct 01 2020 Olivier Stasse <ostasse@laas.fr> - 4.10.1-1
- Autogenerated by Bloom

